title: "BarBeQue report"
subtitle: "Characterization of primers for metabarcoding"
custom_logo: "pipelinelogo.png"
custom_logo_title: "BarBeQue"
custom_logo_url: "http://www.github.com/bio-raum/BarBeQue"
skip_versions_section: true

extra_fn_clean_exts:
    - _R1
    - _R2
    - _duplicate_metrics.txt
    - .pass

report_comment: >
    This report has been generated automatically by bio-raum/BarBeQue.
    For help interpreting the outputs, please see: https://github.com/bio-raum/BarBeQue
report_header_info:
    - Application Type: "Metabarcoding"

top_modules:
    - 'general_stats'

report_section_order:
    software_versions:
        order: -1001
